name: construir_pdf
on: 
  workflow_dispatch:
  schedule: 
    - cron: '00 05 * * *'


jobs:
  build-pdf:
    name: Construir el PDF

    runs-on: ubuntu-latest
    container: asmilex/raytracing

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Compile pdf documentation
        run: |
          cd docs
          make PANDOC_EXEC=pandoc pdf
      
      - name: Set Tag Name
        id: set-tag-name
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            # Manual trigger
            echo "TAG_NAME=manual-$(date -u +'%Y-%m-%d-%H-%M')" >> $GITHUB_ENV
          else
            # Cron job trigger
            echo "TAG_NAME=nightly-$(date -u +'%Y-%m-%d')" >> $GITHUB_ENV
          fi

      - name: Create tag
        if: success()
        run: |
          git tag $TAG_NAME
          git tag push $TAG_NAME

      - name: Create release with pdf
        if: success()
        uses: softprops/action-gh-release@v1
        with:
          files: ./docs/TFG.pdf
          tag_name: ${{ env.tag_name }}
          body: "Release new pdf"

      # - uses: actions/upload-pages-artifact@v2
      #   with:
      #     name: pdf
      #     path: ./docs/TFG.pdf