name: construir_pdf
on: 
  workflow_dispatch:
  workflow_call:

jobs:
  build-pdf:
    name: Construir el PDF

    runs-on: ubuntu-latest
    container:
      image: lucasfa/pandoc_tfg:1.0
      volumes: 
        - ${{ github.workspace }}:/docs

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Compile pdf documentation
        run: |
          cd docs
          make PANDOC_EXEC=pandoc pdf

      - name: Set TAG_NAME
        run: |
          echo "TAG_NAME=$(date -u +'%Y-%m-%d_UTC_%H-%M')" >> $GITHUB_ENV

      - name: Create tag
        if: success()
        uses: rickstaa/action-create-tag@v1
        id: "create_tag"
        with:
          tag: ${{ env.TAG_NAME}}

      - name: Create release with pdf
        if: success()
        uses: softprops/action-gh-release@v1
        with:
          files: ./docs/output/TFG.pdf
          tag_name: ${{ env.TAG_NAME }}
          body: "Release new pdf"

