name: construir_pdf
on: 
  workflow_dispatch:
  schedule: 
    - cron: '00 05 * * *'


jobs:
  build-pdf:
    name: Construir el PDF

    runs-on: ubuntu-latest
    container: asmilex/raytracing

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Enable Debug Logging
        env:
          ACTIONS_RUNNER_DEBUG: true
        run: echo "Debug logging is enabled"

      - name: Compile pdf documentation
        run: |
          cd docs
          make PANDOC_EXEC=pandoc pdf
      
          
      - name: Set TAG_NAME 2
        if: "! ${{ github.event_name == 'workflow_dispatch' }}"
        run: |
          echo "TAG_NAME=nightly-$(date -u +'%Y-%m-%d-%H-M')" >> $GITHUB_ENV

      - name: Set TAG_NAME
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "TAG_NAME=manual-$(date -u +'%Y-%m-%d-%H-%M')" >> $GITHUB_ENV

      - name: debug 
        run: |
          echo ${{ env.TAG_NAME }}

      - name: Create tag
        if: success()
        uses: rickstaa/action-create-tag@v1
        id: "create_tag"
        with:
          tag: ${{ env.TAG_NAME}}

      - name: Create release with pdf
        if: success()
        uses: softprops/action-gh-release@v1
        with:
          files: ./docs/TFG.pdf
          tag_name: ${{ env.TAG_NAME }}
          body: "Release new pdf"

      # - uses: actions/upload-pages-artifact@v2
      #   with:
      #     name: pdf
      #     path: ./docs/TFG.pdf