name: Construir pdf
on: 
  workflow_call:

jobs:
  build-pdf:
    name: Construir el PDF

    runs-on: ubuntu-latest
    container:
      image: lucasfa/pandoc_tfg:asmi_rt
      volumes: 
        - ${{ github.workspace }}/docs:/data

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Compile pdf documentation
        run: |
          cd docs
          make PANDOC_EXEC=pandoc pdf

      - uses: actions/upload-artifact@v3
        if: success()
        with:
          name: pdf
          path: ./docs/TFG.pdf
          if-no-files-found: error

