name: Publicar pdf manualmente
on: 
  workflow_dispatch:

jobs:
  build-pdf:
    uses: ./.github/workflows/build-pdf.yml

  publish-pdf:
    name: Tag pdf artifact
    needs: build-pdf    
    permissions:
      pages: write
      id-token: write

    runs-on: ubuntu-latest

    steps:
      - name: Download pdf
        uses: actions/download-artifact@v3
        with:
          name: pdf

      - name: Rename pdf
        run: |
          echo "PDF_NAME=$(date -u +'%Y-%m-%d_UTC_%H-%M')" >> $GITHUB_ENV
          mv pdf ./${{ env.PDF_NAME}}

      - name: Update nightly release
        uses: pyTooling/Actions/releaser@main
        with:
          tag: manual-release
          rm: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ./${{ env.PDF_NAME}}

