name: Publicar pdf manualmente
on: 
  workflow_dispatch:

jobs:
  build-pdf:
    uses: ./.github/workflows/build-pdf.yml

  publish-pdf:
    name: Tag pdf artifact
    needs: build-pdf    
    permissions:
      pages: write
      id-token: write

    runs-on: ubuntu-latest

    steps:
      - name: Download pdf
        uses: actions/download-artifact@v3
        with:
          name: pdf

      - name: Set TAG_NAME
        run: |
          echo "TAG_NAME=$(date -u +'%Y-%m-%d_UTC_%H-%M')" >> $GITHUB_ENV

      - name: Create tag
        if: success()
        uses: rickstaa/action-create-tag@v1
        id: "create_tag"
        with:
          tag: ${{ env.TAG_NAME}}

      - name: Create release with pdf
        if: success()
        uses: softprops/action-gh-release@v1
        with:
          files: ./TFG.pdf
          tag_name: ${{ env.TAG_NAME }}
          body: "Release new pdf"

