name: construir_pdf
on: 
  schedule: 
    - cron: '00 03 * * *'


jobs:
  build-pdf:
    name: Construir el PDF

    runs-on: ubuntu-latest
    container:
      image: lucasfa/pandoc_tfg:1.0
      volumes: 
        - ${{ github.workspace }}/docs

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Compile pdf documentation
        run: |
          cd docs
          make PANDOC_EXEC=pandoc pdf
 
      - name: Update nightly release
        uses: pyTooling/Actions/releaser@main
        with:
          tag: nightly
          rm: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ./docs/TFG.pdf
