name: Nightly pdf update
on: 
  schedule: 
    - cron: '00 03 * * *'

jobs:
  build-pdf:
    uses: ./.github/workflows/build-pdf.yml

  publish-pdf:
    name: Tag pdf artifact
    needs: build-pdf    
    permissions:
      pages: write
      id-token: write

    runs-on: ubuntu-latest

    steps:
      - name: Download pdf
        uses: actions/download-artifact@v3
        with:
          name: pdf

      - name: Update nightly release
        uses: pyTooling/Actions/releaser@main
        with:
          tag: nightly
          rm: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ${{ GITHUB_WORKSPACE }}/pdf
